version: "3.8"
   
services:
  db:
    restart: always
    container_name: postgres
    image: "postgres:11.2"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
  web:
    container_name: backend
    build:
      context: './backend'
      dockerfile: '../compose/local/django/Dockerfile'
    image: 'todoapp_api'
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    
    depends_on:
      - db
  
  frontend:
    container_name: frontend
    build:
      context: './frontend'
      dockerfile: '../compose/local/react/Dockerfile'
    image: 'todoapp_client'
    ports:
      - "3000:3000"
    command: npm start
    volumes:
    - ./frontend:/app

volumes:
  postgres_data: